server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: fspApplication
  datasource:
    username: borjitascode
    password: password
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
